package init.app.domain.model.enumeration;

public enum NotificationType {
    FOLLOWED, COMMENTED, REPLIED_TO_COMMENT, MENTIONED, SHARED, VOTED, REPOSTED, LIKED//, FOLLOW_COMMENTED, REPLIED_MY_ARTICLE, FOLLOW_REPLIED, FOLLOW_SHARED, VOTED, FOLLOW_VOTED
}
